#!/usr/bin/python

import setup
setup.pre_install()

from charmhelpers.core import hookenv
from charmhelpers import fetch
from charmhelpers.core import host
from charmhelpers.fetch import archiveurl


def install():
    hookenv.log('Installing saiku')
    # add steps for installing dependencies and packages here

    host.mkdir('/usr/local/SaikuCE')
    ##Need to create a saiku user for security.
    fetch.apt_install(fetch.filter_installed_packages(['openjdk-7-jdk']))
    handler = archiveurl.ArchiveUrlFetchHandler()
#    handler.install('http://meteorite.bi/downloads/saiku-latest.tar.gz', '/usr/local/SaikuCE')

if __name__ == "__main__":
    install()
