#!/bin/bash

# This script installs the OpenMRS Charm in Juju.  See the ../README for more 
# information about the OpenMRS Charm.

# Abort the script if any errors are encountered.
set -e
# Show the commands that are getting executed.
set -x

container=tomcat7
if [[ -e /var/lib/tomcat7 ]]; then
  container=tomcat7
elif [[ -e /var/lib/tomcat6 ]]; then
  container=tomcat6
fi

if [ ! -d /usr/share/${container} ]; then
  juju-log --log-level CRITICAL "${container} is not installed properly!"
  exit 1
fi

openmrs_directory="/usr/share/saiku_ce"
if [ ! -d ${openmrs_directory} ]; then
  mkdir ${openmrs_directory}
  chmod 777 ${openmrs_directory}
fi

# Install any tools that are needed for the install of OpenMRS.
apt-get install -y wget coreutils unzip

# Define the download location for OpenMRS.
openmrs_url=http://192.168.1.108/saiku.zip
root_url=http://192.168.1.108/ROOT.zip
data_url=http://192.168.1.108/data.tgz
repository_url=http://192.168.1.108/repository.tgz

juju-log "Downloading OpenMRS from ${openmrs_url} to ${openmrs_directory}"
# Download the OpenMRS file into the openmrs directory.
wget "${openmrs_url}" -O ${openmrs_directory}/saiku.war
wget "${root_url}" -O ${openmrs_directory}/ROOT.war
wget "${data_url}" -O ${openmrs_directory}/data.tgz
tar xvfz ${openmrs_directory}/data.tgz -C ${openmrs_directory}
wget "${repository_url}" -O ${openmrs_directory}/repository.tgz
tar xvfz ${openmrs_directory}/repository.tgz -C ${openmrs_directory}
unzip -o ${openmrs_directory}/ROOT.war -d /var/lib/${container}/webapps/ROOT
unzip -o ${openmrs_directory}/saiku.war -d /var/lib/${container}/webapps/saiku
chown -R ${container}:${container} ${openmrs_directory}

# The sha1sum for the openmrs.war version 1.9.7
openmrs_1_9_7_sha1sum="97de4c82ba4c9d556c840e50a6624fc47c7ff77e"
# It is best practice to check the hash value for the file that was downloaded.
openmrs_sha1sum=`sha1sum ${openmrs_directory}/saiku.war | cut -d " " -f 1`
if [[ ${openmrs_sha1sum} != ${openmrs_1_9_7_sha1sum} ]]; then
  juju-log --log-level CRITICAL "The SHA1 checksum of ${openmrs_url} is invalid."
  juju-log --log-level CRITICAL "The checksum of the openmrs.war was ${openmrs_sha1sum}"
  juju-log --log-level CRITICAL "Expected ${openmrs_1_9_7_sha1sum}"
  exit 1
else 
  juju-log "The SHA1 checksum of ${openmrs_directory}/openmrs.war was valid."
fi

# Stop tomcat.
$CHARM_DIR/hooks/stop